name: Publish preview update

defaults:
  tools:
    node: 20.19.4

jobs:
  publish_preview_update:
    name: Publish preview update
    environment: preview
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
        working_directory: ./RunTogether
      - name: Publish update
        working_directory: ./RunTogether
        run: npx --package eas-cli eas update --branch preview --non-interactive --message "Preview update"
